name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master # Change 'main' to 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Ensure this matches the version mentioned in your error

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Adjust this command as per your project setup

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token "$FIREBASE_SERVICE_ACCOUNT_TIC_TAC_TOE_32B02" --project "tic-tac-toe-32b02"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIC_TAC_TOE_32B02 }}
