name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Make sure this command builds your project using vite or appropriate build tool

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIC_TAC_TOE_32B02 }}
          channelId: live
          projectId: tic-tac-toe-32b02
